import enum


class CanonicalBucket(str, enum.Enum):
    RECEIPT = "RECEIPT"
    DELIVERY = "DELIVERY"
    RETURN_IN = "RETURN_IN"
    TRANSFER = "TRANSFER"
    TRANSFER_3P = "TRANSFER_3P"
    PRODUCTION_CONSUMPTION = "PRODUCTION_CONSUMPTION"
    FINISHED_GOOD_OUTPUT = "FINISHED_GOOD_OUTPUT"
    ADJUSTMENT = "ADJUSTMENT"
    DELIVERY_REVERSAL = "DELIVERY_REVERSAL"
    REGULARIZATION = "REGULARIZATION"
    REVIEW = "REVIEW"
